services:
  builder:
    image: electronuserland/builder:18-wine
    volumes:
      - ./:/project
    # Enable caching for faster rebuilds
    # environment:
    #   ELECTRON_CACHE: "/project/.cache/electron"
    #   ELECTRON_BUILDER_CACHE: "/project/.cache/electron-builder"
    command: sh -c '
      npm install --loglevel=info &&
      npm run dist:linux &&
      npm run dist:windows &&
      npm run dist:macos
      '
